// This is Auto Generated Script so any modification will overwrite

using UnityEditor;

public class SceneUtilAutoGenerated
{
    [MenuItem("Scenes/StartScene")]
    public static void GeneratedStartSceneMethod()
    {
        var scenePath = "Assets/Scenes/StartScene.unity";
        SceneUtil.SceneEditorUtil.OpenScene(scenePath);
    }

    [MenuItem("Scenes/GameScene")]
    public static void GeneratedGameSceneMethod()
    {
        var scenePath = "Assets/Scenes/GameScene.unity";
        SceneUtil.SceneEditorUtil.OpenScene(scenePath);
    }

    [MenuItem("Scenes/GameOverScene")]
    public static void GeneratedGameOverSceneMethod()
    {
        var scenePath = "Assets/Scenes/GameOverScene.unity";
        SceneUtil.SceneEditorUtil.OpenScene(scenePath);
    }

}
